import app from "./expressApp";
import userRoutes from "../routes/user";
import categoriesRoutes from "../routes/categories";
import productsRoutes from "../routes/products";
import customersRoutes from "../routes/customers";
import sellersRoutes from "../routes/sellers";
import vendorsRoutes from "../routes/vendors";
import reviewsRoutes from "../routes/reviews";
import promotionsRoutes from "../routes/promotions";
import ordersRoutes from "../routes/orders";
import order_itemsRoutes from "../routes/order_items";
import order_returnsRoutes from "../routes/order_returns";
import order_fulfillmentsRoutes from "../routes/order_fulfillments";
import order_refundsRoutes from "../routes/order_refunds";
import dealsRoutes from "../routes/deals";
import deal_productsRoutes from "../routes/deal_products";
import billing_addressesRoutes from "../routes/billing_addresses";
import shipping_addressesRoutes from "../routes/shipping_addresses";
import winnersRoutes from "../routes/winners";
import deal_entriesRoutes from "../routes/deal_entries";
import deliveriesRoutes from "../routes/deliveries";
import user_addressRoutes from "../routes/user_addresses";
// import setupBillingRoutes from '../routes/setup_billing';

app.use("/api/v1", userRoutes);
app.use("/api/v1", categoriesRoutes);
app.use("/api/v1", productsRoutes);
app.use("/api/v1", customersRoutes);
app.use("/api/v1", sellersRoutes);
app.use("/api/v1", vendorsRoutes);
app.use("/api/v1", reviewsRoutes);
app.use("/api/v1", promotionsRoutes);
app.use("/api/v1", ordersRoutes);
app.use("/api/v1", order_itemsRoutes);
app.use("/api/v1", order_fulfillmentsRoutes);
app.use("/api/v1", order_returnsRoutes);
app.use("/api/v1", order_refundsRoutes);
app.use("/api/v1", dealsRoutes);
app.use("/api/v1", deal_productsRoutes);
app.use("/api/v1", billing_addressesRoutes);
app.use("/api/v1", shipping_addressesRoutes);
app.use("/api/v1", user_addressRoutes);
app.use("/api/v1", winnersRoutes);
app.use("/api/v1", deal_entriesRoutes);
app.use("/api/v1", deliveriesRoutes);

// app.use('/api/v1', setupBillingRoutes);

export default app;
