export default (sequelize: any, DataTypes: any) => {
  const Products = sequelize.define(
    "products",
    {
      id: {
        type: DataTypes.SMALLINT,
        primaryKey: true,
        autoIncrement: true
      },
      productCode: DataTypes.STRING,
      productName: DataTypes.STRING,
      product_id: DataTypes.STRING,
      price_id: DataTypes.STRING,
      sellerId: DataTypes.SMALLINT,
      domainName: DataTypes.STRING,
      sellerName: DataTypes.STRING,
      categoryId: DataTypes.SMALLINT,
      categoryName: DataTypes.STRING,
      categoryCode: DataTypes.STRING,
      skuParent: DataTypes.STRING,
      sku: DataTypes.STRING,
      brandName: DataTypes.STRING,
      description: DataTypes.STRING,
      color: DataTypes.STRING,
      condition: DataTypes.STRING,
      variants: DataTypes.STRING,
      department: DataTypes.STRING,
      imageUrlMain: DataTypes.STRING,
      imageUrlOther1: DataTypes.STRING,
      imageUrlOther2: DataTypes.STRING,
      imageUrlOther3: DataTypes.STRING,
      imageUrlOther4: DataTypes.STRING,
      imageUrlOther5: DataTypes.STRING,
      imageUrlOther6: DataTypes.STRING,
      imageUrlOther7: DataTypes.STRING,
      gender: DataTypes.STRING,
      likes: DataTypes.SMALLINT,
      catCode1: DataTypes.STRING,
      catLevel1: DataTypes.STRING,
      catCode2: DataTypes.STRING,
      catLevel2: DataTypes.STRING,
      currencyCode: DataTypes.STRING,
      unitCost: DataTypes.DECIMAL,
      unitPrice: DataTypes.DECIMAL,
      altPrice: DataTypes.DECIMAL,
      size: DataTypes.STRING,
      unitsInStock: DataTypes.SMALLINT,
      deliveryDays: DataTypes.SMALLINT,
      bulletPoint1: DataTypes.STRING,
      bulletPoint2: DataTypes.STRING,
      bulletPoint3: DataTypes.STRING,
      bulletPoint4: DataTypes.STRING,
      bulletPoint5: DataTypes.STRING,
      bulletPoint6: DataTypes.STRING,
      bulletPoint7: DataTypes.STRING,
      variantIds: DataTypes.STRING,
      keywords: DataTypes.STRING,
      percentage: DataTypes.DECIMAL,
      shippingCost: DataTypes.DECIMAL,
      length: DataTypes.DECIMAL,
      height: DataTypes.DECIMAL,
      weight: DataTypes.DECIMAL,
      weightShipping: DataTypes.DECIMAL,
      uom: DataTypes.STRING,
      uomShipping: DataTypes.STRING,
      leadTimeToShip: DataTypes.SMALLINT,
      colorList: DataTypes.STRING,
      reorderLevel: DataTypes.SMALLINT,
      header: DataTypes.STRING,
      footer: DataTypes.STRING,
      isTaxed: DataTypes.BOOLEAN,
      imageSmall: DataTypes.STRING,
      imageMedium: DataTypes.STRING,
      imageLarge: DataTypes.STRING,
      imageList: DataTypes.STRING,
      variantName1: DataTypes.STRING,
      variantName2: DataTypes.STRING,
      variantName3: DataTypes.STRING,
      productOrder: DataTypes.SMALLINT,
      manufacturer: DataTypes.STRING,
      upc: DataTypes.STRING,
      countryMadeIn: DataTypes.STRING,
      modelNumber: DataTypes.STRING,
      legalDisclaimer: DataTypes.STRING,
      scent: DataTypes.STRING,
      flavor: DataTypes.STRING,
      ageMinimum: DataTypes.SMALLINT,
      ageMaximum: DataTypes.SMALLINT,
      videoLink: DataTypes.STRING,
      dateFeaturedExpiry: DataTypes.STRING,
      dateLaunch: DataTypes.STRING,
      dateRelease: DataTypes.STRING,
      status: DataTypes.STRING,
      modified_at: DataTypes.DATE,
      created_at: DataTypes.DATE
    },
    {
      freezeTableName: true
    }
  );
  return Products;
};
